import { TSuggestion } from "types/suggestion/suggestion.types";

export const suggestions: TSuggestion[] = [
  {
    Id: 1,
    CompanyId: "445",
    EmployeeId: "9866",
    Material: "Material 1",
    PharmaceuticalFormId: 1,
    OtherPharmaceuticalFormId: 2,
    PharmaceuticalForm_Other: "",
    OtherPharmaceuticalForm_Other: "",
    BrandName: "گلرنگ  دارو",
    ManufacturerCompanyName: "گروه گلرنگ",
    Consumable: "Consumable1",
    TherapeuticFieldId: 1,
    TherapeuticFieldComment: "TherapeuticFieldComment1",
    OfferReasonId: 1,
    OfferReasonComment: "OfferReasonComment1",
    ProductAdvatage: "ProductAdvatage1",
    ProductWeaknesses: "ProductWeaknesses1",
    SimilarPharmaceuticalForm: true,
    SimilarTherapeuticField: true,
    SimilarConsumable: true,
    Comment: "Comment1",
    Modified: "2023-03-20T13:29:58Z",
    Created: "2023-02-29T14:49:29Z",
  },

  {
    Id: 2,
    CompanyId: "445",
    EmployeeId: "10857",
    Material: "Material 2",
    PharmaceuticalFormId: 2,
    OtherPharmaceuticalFormId: 3,
    PharmaceuticalForm_Other: "",
    OtherPharmaceuticalForm_Other: "",
    BrandName: "2گلرنگ  دارو",
    ManufacturerCompanyName: "2گروه گلرنگ",
    Consumable: "Consumable2",
    TherapeuticFieldId: 2,
    TherapeuticFieldComment: "TherapeuticFieldComment2",
    OfferReasonId: 2,
    OfferReasonComment: "OfferReasonComment2",
    ProductAdvatage: "ProductAdvatage2",
    ProductWeaknesses: "ProductWeaknesses2",
    SimilarPharmaceuticalForm: true,
    SimilarTherapeuticField: true,
    SimilarConsumable: true,
    Comment: "Comment2",
    Modified: "2023-01-23T13:06:08Z",
    Created: "2023-03-22T14:49:29Z",
  },

  {
    Id: 3,
    CompanyId: "445",
    EmployeeId: "3943",
    Material: "Material 3",
    PharmaceuticalFormId: 3,
    OtherPharmaceuticalFormId: 2,
    PharmaceuticalForm_Other: "",
    OtherPharmaceuticalForm_Other: "",
    BrandName: "گلرنگ  دارو",
    ManufacturerCompanyName: "گروه گلرنگ",
    Consumable: "Consumable3",
    TherapeuticFieldId: 3,
    TherapeuticFieldComment: "TherapeuticFieldComment3",
    OfferReasonId: 3,
    OfferReasonComment: "OfferReasonComment3",
    ProductAdvatage: "ProductAdvatage3",
    ProductWeaknesses: "ProductWeaknesses3",
    SimilarPharmaceuticalForm: true,
    SimilarTherapeuticField: true,
    SimilarConsumable: true,
    Comment: "Comment3",
    Modified: "2023-04-13T13:06:08Z",
    Created: "2023-02-12T14:49:29Z",
  },

  {
    Id: 4,
    CompanyId: "445",
    EmployeeId: "3948",
    Material: "Material 4",
    PharmaceuticalFormId: 4,
    OtherPharmaceuticalFormId: 2,
    PharmaceuticalForm_Other: "",
    OtherPharmaceuticalForm_Other: "",
    BrandName: "گلرنگ  دارو",
    ManufacturerCompanyName: "گروه گلرنگ",
    Consumable: "Consumable4",
    TherapeuticFieldId: 3,
    TherapeuticFieldComment: "TherapeuticFieldComment4",
    OfferReasonId: 2,
    OfferReasonComment: "OfferReasonComment4",
    ProductAdvatage: "ProductAdvatage4",
    ProductWeaknesses: "ProductWeaknesses4",
    SimilarPharmaceuticalForm: true,
    SimilarTherapeuticField: true,
    SimilarConsumable: true,
    Comment: "Comment4",
    Modified: "2023-02-23T13:06:08Z",
    Created: "2023-02-22T14:49:29Z",
  },

  {
    Id: 5,
    CompanyId: "445",
    EmployeeId: "3934",
    Material: "Material 5",
    PharmaceuticalFormId: 5,
    OtherPharmaceuticalFormId: 2,
    PharmaceuticalForm_Other: "",
    OtherPharmaceuticalForm_Other: "",
    BrandName: "گلرنگ  دارو",
    ManufacturerCompanyName: "گروه گلرنگ",
    Consumable: "Consumable5",
    TherapeuticFieldId: 2,
    TherapeuticFieldComment: "TherapeuticFieldComment5",
    OfferReasonId: 1,
    OfferReasonComment: "OfferReasonComment5",
    ProductAdvatage: "ProductAdvatage5",
    ProductWeaknesses: "ProductWeaknesses5",
    SimilarPharmaceuticalForm: true,
    SimilarTherapeuticField: true,
    SimilarConsumable: true,
    Comment: "Comment5",
    Modified: "2023-02-23T13:06:08Z",
    Created: "2023-02-22T14:49:29Z",
  },

  {
    Id: 6,
    CompanyId: "445",
    EmployeeId: "3935",
    Material: "Material 6",
    PharmaceuticalFormId: 6,
    OtherPharmaceuticalFormId: 2,
    PharmaceuticalForm_Other: "",
    OtherPharmaceuticalForm_Other: "",
    BrandName: "گلرنگ  دارو",
    ManufacturerCompanyName: "گروه گلرنگ",
    Consumable: "Consumable6",
    TherapeuticFieldId: 2,
    TherapeuticFieldComment: "TherapeuticFieldComment6",
    OfferReasonId: 1,
    OfferReasonComment: "OfferReasonComment6",
    ProductAdvatage: "ProductAdvatage6",
    ProductWeaknesses: "ProductWeaknesses6",
    SimilarPharmaceuticalForm: true,
    SimilarTherapeuticField: true,
    SimilarConsumable: true,
    Comment: "Comment6",
    Modified: "2023-02-23T13:06:08Z",
    Created: "2023-02-22T14:49:29Z",
  },

  {
    Id: 7,
    CompanyId: "445",
    EmployeeId: "10092",
    Material: "Material 7",
    PharmaceuticalFormId: 3,
    OtherPharmaceuticalFormId: 2,
    PharmaceuticalForm_Other: "",
    OtherPharmaceuticalForm_Other: "",
    BrandName: "گلرنگ  دارو",
    ManufacturerCompanyName: "گروه گلرنگ",
    Consumable: "Consumable7",
    TherapeuticFieldId: 1,
    TherapeuticFieldComment: "TherapeuticFieldComment7",
    OfferReasonId: 1,
    OfferReasonComment: "OfferReasonComment7",
    ProductAdvatage: "ProductAdvatage7",
    ProductWeaknesses: "ProductWeaknesses7",
    SimilarPharmaceuticalForm: true,
    SimilarTherapeuticField: true,
    SimilarConsumable: true,
    Comment: "Comment7",
    Modified: "2023-02-23T13:06:08Z",
    Created: "2023-02-22T14:49:29Z",
  },

  {
    Id: 8,
    CompanyId: "445",
    EmployeeId: "10092",
    Material: "Material 8",
    PharmaceuticalFormId: 8,
    OtherPharmaceuticalFormId: 2,
    PharmaceuticalForm_Other: "",
    OtherPharmaceuticalForm_Other: "",
    BrandName: "گلرنگ  دارو",
    ManufacturerCompanyName: "گروه گلرنگ",
    Consumable: "Consumable8",
    TherapeuticFieldId: 2,
    TherapeuticFieldComment: "TherapeuticFieldComment8",
    OfferReasonId: 2,
    OfferReasonComment: "OfferReasonComment8",
    ProductAdvatage: "ProductAdvatage8",
    ProductWeaknesses: "ProductWeaknesses8",
    SimilarPharmaceuticalForm: true,
    SimilarTherapeuticField: true,
    SimilarConsumable: true,
    Comment: "Comment8",
    Modified: "2023-02-23T13:06:08Z",
    Created: "2023-02-22T14:49:29Z",
  },

  {
    Id: 9,
    CompanyId: "445",
    EmployeeId: "9866",
    Material: "Material 9",
    PharmaceuticalFormId: 8,
    OtherPharmaceuticalFormId: 2,
    PharmaceuticalForm_Other: "",
    OtherPharmaceuticalForm_Other: "",
    BrandName: "گلرنگ  دارو",
    ManufacturerCompanyName: "گروه گلرنگ",
    Consumable: "Consumable9",
    TherapeuticFieldId: 3,
    TherapeuticFieldComment: "TherapeuticFieldComment9",
    OfferReasonId: 5,
    OfferReasonComment: "OfferReasonComment9",
    ProductAdvatage: "ProductAdvatage9",
    ProductWeaknesses: "ProductWeaknesses9",
    SimilarPharmaceuticalForm: true,
    SimilarTherapeuticField: true,
    SimilarConsumable: true,
    Comment: "Comment9",
    Modified: "2023-02-23T13:06:08Z",
    Created: "2023-02-22T14:49:29Z",
  },
];

export const offerResons = [
  { Id: 1, Title: "مكمل سبد" },
  { Id: 2, Title: "اندازه بازار بالا" },
  { Id: 3, Title: "اولین تولید کننده" },
  { Id: 4, Title: "کنگره يا پیشنهاد پزشک KOL" },
  { Id: 5, Title: "کمبود در بازار" },
  { Id: 6, Title: "ساير" },
];

export const therapeuticField = [
  { Id: 1, Title: "تقويت سیستم ايمنی" },
  { Id: 2, Title: "گوارش" },
  { Id: 3, Title: "تغذيه" },
  { Id: 4, Title: "ساير" },
];

export const pharmaceuticalForms = [
  { Id: 1, Title: "قرص" },
  { Id: 2, Title: "کپسول" },
  { Id: 3, Title: "سافت ژل" },
  { Id: 4, Title: "شربت" },
  { Id: 5, Title: "قطره" },
  { Id: 6, Title: "شیاف" },
  { Id: 7, Title: "فرآورده های موضعی" },
  { Id: 8, Title: "ساير" },
];
