export const queryKeys = {
  getPharmaceuticalForms: "getPharmaceuticalForms",
  getTherapeuticField: "getTherapeuticField",
  allEmployee: "allEmployee",
  getAllSuggestion: "getAllSuggestion",
  getOfferReason: "getOfferReason",
  getPriority: "getPriority",
  getOfferResult: "getOfferResult",
  getHistoryOfActions: "getAllLogs",
  getConfirmationDocuments: "getAllConfirmationDocuments",
  getProductsSuggestion: "getProductsSuggestion",
  getAllAction: "getAllAction",
  getAllStep: "getAllStep",
  getAllFlow: "getAllFlow",
  getFlowByCurrent: "getFlowByCurrent",
  getDevExpertHeadGroup: "getDevExpertHeadGroup",
  getDevExpertGroup: "getDevExpertGroup",
  getEvaluationStudiesGroup: "getEvaluationStudiesGroup",
  getAllSuggestionById: "getAllSuggestionById",
  getAllPrioritization: "getAllPrioritization",
  getAllResultOfSuggestion: "getAllResultOfSuggestion",
  getResultOfSuggestionById: "getResultOfSuggestionById",
};
