export const queryKeys = {
  getPharmaceuticalForms: "getPharmaceuticalForms",
  getTherapeuticField: "getTherapeuticField",
  allEmployee: "allEmployee",
  getAllSuggestion: "getAllSuggestion",
  getOfferReason: "getOfferReason",
  getPriority: "getPriority",
  getOfferResult: "getOfferResult",
  getHistoryOfActions: "getAllLogs",
  getConfirmationDocuments: "getAllConfirmationDocuments",
  getProductsSuggestion: "getProductsSuggestion",
  getAllAction: "getAllAction",
  getAllStep: "getAllStep",
  getDevExpertHeadGroup: "getDevExpertHeadGroup",
  getDevExpertGroup: "getDevExpertGroup",
  getEvaluationStudiesGroup: "getEvaluationStudiesGroup",
};
